### PR TITLE
Update licenses and get code to work on Stable

### PR DESCRIPTION
**Pull request by mgattozzi**

### CODE REVIEW

**Comment by TheDoctorsLife** [comment]
Going to put this here, but I've also been busy with school work and whatnot, and am only within the past few weeks or so have I been able to contribute code to anything. I hope that I can continue helping with this project when I can, but may not always be able to... as I see is the same with you.

**Comment by TheDoctorsLife** [comment]
I also want to bring to your attention [this](https://bors-ng.github.io/)

**Comment by mgattozzi** [comment]
@TheDoctorsLife awesome I just redid a bunch of stuff so I'll add you on as a contributor. Just push code to prs so I can review! I did see that. I'm actually working on a bot myself actually.
https://github.com/mgattozzi/thearesia/

**Comment by mgattozzi** [comment]
Also you might want to do a fresh clone of this. I had to do some force pushes to clean up master and whatnot.

**Comment by TheDoctorsLife** [comment]
nah fresh clones are for wimps, all the cool kids are doing using ``git rebase`` these days.

I had a data lose incident so I didn't have a local copy till now, so its all good.

**Comment by TheDoctorsLife** [comment]
I wondering if we could look into using something like Discord or IRC to replace slack in the line of messaging outside of github (for things that may need it)

**Comment by mgattozzi** [comment]
Yeah I was thinking so too. I'm inclined to use IRC but discord would maintain history and allows more asynchronous communication.

**Comment by TheDoctorsLife** [comment]
I went ahead an made a new discord server, https://discord.gg/C45GR

**Comment by TheDoctorsLife** [comment]
Travis is broken for this repo it seems.

**Comment by mgattozzi** [comment]
@TheDoctorsLife Looks like it's good actually! I'll have to jump on discord later. I don't have it installed anywhere on any of my systems

**Pull request merged**
